---
title: "Customer Segmentation for E-commerce using K-means Clustering"
author: "Vishal Reddy Jakkareddy"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: Capstone Projects in Data Science
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

Slides: [slides.html](slides.html){target="_blank"} ( Go to `slides.qmd`
to edit)


## Introduction

#### K-Means Clustering Approach for Intelligent Customer Segmentation Using Customer Purchase Behavior Data [@tabianan2022k]:
- This study applies the K-Means clustering algorithm to perform intelligent customer segmentation based on e-commerce purchase behavior data. Customer segmentation is crucial for dividing customers into groups with similar characteristics, enabling businesses to target the right audience effectively and boost profitability. Using a Malaysian e-commerce dataset, the research analyzes customer behavior to identify and categorize high, moderate, and low-interest customer segments. The proposed SAPK + K-Means algorithm demonstrates improved accuracy over traditional methods like Affinity Propagation and standard K-Means. The study emphasizes the role of segmentation in optimizing marketing strategies, improving customer retention, and increasing revenue. Data visualization dashboards are also used to present actionable insights, making it easier for businesses to understand and act on customer behavior. Despite limitations like microdata volatility, the research sets the groundwork for future studies to explore deep learning methods for enhanced segmentation.


#### Customer Segmentation of E-commerce data using K-means Clustering Algorithm [@10048834]:
- This study explores the application of the K-Means clustering algorithm for customer segmentation in e-commerce. By analyzing a dataset of 500 entries with attributes like session length, time spent on mobile apps and websites, membership duration, and yearly spending, the research aims to determine whether the company should focus on its website or mobile app. Using the elbow method to select the optimal number of clusters, three customer segments were identified. The findings suggest that customer behavior, such as membership duration and platform engagement, directly correlates with spending patterns. Recommendations include targeting campaigns to increase customer retention and emphasizing membership benefits for profitability. The study concludes that customer segmentation using K-Means is a practical and efficient method for tailoring marketing strategies in a competitive e-commerce environment.

